---
namespace: "tcharl"
name: "ansible_localuser"
version: "0.0.1"
description: "Ansible roles to manage local linux users and groups"

authors:
  - "Charlie Mordant <cmordant1@gmail.com>"

repository: "https://github.com/freeipa/ansible-freeipa"
documentation: "https://github.com/freeipa/ansible-freeipa/blob/master/README.md"
homepage: "https://github.com/freeipa/ansible-freeipa"
issues: "https://github.com/freeipa/ansible-freeipa/issues"

readme: "README.md"
license:
  - "Apache-2.0"
tags:
  - "linux"
  - "system"
  - "identity"
