---
dependency:
  name: galaxy
  options:
    role-file: requirements-standalone.yml
    requirements-file: requirements-collections.yml
driver:
  name: docker
platforms:
  - name: ansible-users-vm
    image: fedora:38
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: yes
    pre_build_image: yes
provisioner:
  name: ansible
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore:.*U.*mode is deprecated:DeprecationWarning"
  options:
    v: 1
