---
# This is a basic workflow to help you get started with Actions
name: Molecule

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
  pull_request:
    branches:
      - master
      - tags/*

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  requirements:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: install prereq
        run: |
          ansible-galaxy role install -r requirements-standalone.yml
          ansible-galaxy collection install -r requirements-collections.yml

  molecule:
    runs-on: ubuntu-latest
      # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: add docker apt key
        run: |
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      - name: add docker apt repository
        run: |
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
      - name: update apt
        run: |
          sudo apt update
#      - name: apt upgrade
#        run: |
#          sudo apt upgrade

      - name: install tests prerequisite
        run: |
          sudo apt -y install bridge-utils dnsmasq-base ebtables ca-certificates curl gcc iproute2 sudo rustc python3 python3-pip python3-setuptools docker-ce docker-ce-cli containerd.io
      - name: Install molecule
        run: |
          pip3 install wheel setuptools setuptools-rust tox
      - name: execute lint
        run: |
          ln -s ../ansible-localuser ../tcharl.ansible_localuser
          cd ../tcharl.ansible_localuser
          tox -e lint

      - name: execute tests
        run: |
          ln -s ../ansible-localuser ../tcharl.ansible_localuser | true
          cd ../tcharl.ansible_localuser
          tox -e test-exec
