---

- name: Local-groups | manage local-group with robertdebock role
  ansible.builtin.include_role:
    name: robertdebock.users
  vars:
    users_groups: "{{ local_users_group_list | default([]) | json_query(\"[?!freeipa]\") | list }}"
    ansible_become: true
